title: <p align="center"> Piyush R Singh </p>
logo: /assets/img/Piyush Singh.jpg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working on Deep Learning, Machine learning & NLP related problems/projects.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in Insurance domain for 17+ years.
  <br>
  </p>



theme: jekyll-theme-minimal
