title: <p align="center"> Piyush R Singh </p>
logo: /assets/img/Piyush Singh.jpg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/piyush-singh-2303a0185/">LinkedIn</a> |
  <a href="https://github.com/piyushrsingh">GitHub</a>
  
  <br>   
  I'm working on Deep Learning, Machine learning & NLP related problems/projects.
  Also handing the Fraud Detection in Claim FNOL.
  Working with Xceedance as a Product Manager in Digital Transformation.
  Working in Insurance domain for 17+ years.
  <br>
  </p>






theme: jekyll-theme-minimal
